import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState } from "react";

export default function Home() {
  const [loginData, setLoginData] = useState({
    email: "",
    password: "",
  });
  const [steps, setSteps] = useState();
  const [error, setError] = useState({
    email: "",
    password: "",
  });

  function onSubmit() {
    console.log("data", loginData.email);
  }
  function handleBlur(value) {
    if (value === "") {
      setError({
        email: "Email is required",
      });
    } else {
      setError({
        email: "",
      });
    }
   
  }
  // function handleBlurpass(value) {
  //   if ( value === "") {
  //     setError({
  //       password: "password is required",
  //     });
  //   } else {
  //     setError({
  //       password: "",
  //     });
  //   }
  // }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
      </Head>
      <div className="login-form mx-auto my-4">
        <h4>Login</h4>
        <div className="input-group mb-3">
          <label>Email </label>
          <input
            type="text"
            className="form-control"
            onBlur={(e) => {
              setLoginData({
                email: e.target.value,
                password: loginData.password,
              });
              handleBlur(e.target.value);
            }}
          />
          <p>{error?.email}</p>
        </div>
        <div className="input-group mb-3 ">
          <label>Password</label>
          <input
            type="text"
            className="form-control"
            onBlur={(e) => {
              setLoginData({
                email: loginData.email,
                password: e.target.value,
              });
              handleBlur(e.target.value);
            }}
          />
        </div>
        <button className="btn btn-primary" onClick={() => onSubmit()}>
          Login
        </button>
        <div>{JSON.stringify(loginData)}</div>
      </div>
      <div>
        <a>check {steps}</a>
        <button className="btn btn-primary" onClick={() => setSteps(steps + 1)}>
          check Usestate
        </button>
      </div>
    </div>
  );
}
